/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package compiler;

import lombok.extern.slf4j.Slf4j;

@Slf4j
public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        log.info("Starting up!");
        System.out.println(new App().getGreeting());
    }
}
